### ISSUE TITLE
Aktualisierung/Überarbeitung der Folien zum International Day 2024

### ISSUE THREAD

**Issue by chrdrn** [faucommsci/erasmus-program#1]
## ToDos
- [x] Aktualisierung der verschiedenen Daten (vor allem Titelfolie und "Bewerbung")
- [x] Überprüfung auf und Korrektur von kleineren Fehlern (z.B. auf der Folie "Allgemeine Voraussetzungen" statt "(Beispiele)" eine Verlinkung zum Lehrangebot)
- [x] Optional: Ergänzung von weiteren hilfreichen Informationen

Die Überarbeitung sollen in folgender Datei erfolgen: [international_day.qmd](https://github.com/faucommsci/erasmus-program/blob/main/slides/international_day.qmd)

**Comment by chrdrn** [comment]
@emmaleun Vielen Dank für die Überarbeitungen. Der letzten ("optionale") Punkt war an dich gerichtet, ich habe nur vergessen das zu kommunizieren. Deswegen die Frage: Hast du noch Anmerkungen zur Verbesserung oder fehlen Informationen, die du dir gewünscht hättest?

**Comment by chrdrn** [comment]
Worked on in 931c5f5

**Comment by emmaleun** [comment]
@chrdrn Kein Problem, ich dachte nur, dass ich mir die PPP heute nochmals in Ruhe anschaue. :) 
Aber meiner Meinung nach sind die Informationen ausreichend, vor allem für den International Day.
